# Generated by Django 2.1.9 on 2019-06-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_app', '0003_project_image'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_cms_integration_portfoliopluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('portfolio', models.ManyToManyField(to='portfolio_app.Portfolio')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
