# Generated by Django 2.1.9 on 2019-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopluginmodel',
            name='portfolio',
            field=models.ManyToManyField(to='portfolio_app.Portfolio'),
        ),
    ]
