# Generated by Django 2.1.9 on 2019-06-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('portfolio_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_cms_integration_projectpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
