# Generated by Django 2.1.9 on 2019-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_project_image'),
        ('portfolio_cms_integration', '0002_projectpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpluginmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='projectpluginmodel',
            name='author',
            field=models.ManyToManyField(to='portfolio_app.Project'),
        ),
    ]
